### ISSUE TITLE
PubDate gone?

### ISSUE THREAD

**Issue by jboesh** [custom-components/feedparser#101]
versions used:
**HA:** 2019.1
**feedparser:** 0.2.0b0

It appears that the PubDate is not included even though it exists in the feed URL

```
sensor:
  - platform: feedparser
    name: Nieuws
    feed_url: 'https://www.nu.nl/rss'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 1
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language
```

in the sensor only the title, link and image are included but not the date:
![image](https://github.com/custom-components/feedparser/assets/71582854/99e9f41d-3dbf-490b-9625-fd8122ff2154)

the feed url contains the date:
![image](https://github.com/custom-components/feedparser/assets/71582854/f2cd6431-32ad-4e22-a7de-f6f5d6e836c7)

**Comment by ogajduse** [comment]
README is wrong. `feedparser` entry contains `published` attribute that should be used instead of the raw _pubDate_.
Changing `pubDate` to `published` in your config should do the trick.

I will update the readme as a part of #90.

**Comment by ogajduse** [comment]
@jboesh Also, thank you for testing the beta version. There are also newer 0.2.0 beta versions, feel free to try them out. I am eager to hear whether everything works and I did not break anything.

**Comment by jboesh** [comment]
Thanks looks like it's added now as attribute.
But how to add it into the lovelace card?

I've tried to add "published" or "date" but that doesn't work

```
type: custom:list-card
entity: sensor.news
title: News
feed_attribute: entries
row_limit: 5
columns:
  - title: ''
    type: image
    add_link: link
    field: image
  - title: Title
    field: title
    style:
      - white-space: wrap
      - title: Description
        field: description

```
