### ISSUE TITLE
more than one feed_url

### ISSUE THREAD

**Issue by jboesh** [custom-components/feedparser#102]
A quick question. 
If I want to use multiple sources (feed_url), how do I add this in the configuration? It might also be useful for other people to include this on the homepage of your GitHub.

Thanks!

**Comment by ogajduse** [comment]
Thank you for your feedback. I will document it in README as a part of #90.

Here is an example of how you can configure two feeds (sources). Each RSS feed is a separate sensor entry. The configuration below is overly big and not all options are required.

```
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://www.nu.nl/rss
  inclusions:
  - image
  - title
  - link
  - published
  local_time: false
  name: nu_nl
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://www.nu.nl/rss/Algemeen
  inclusions:
  - image
  - title
  - link
  - published
  local_time: false
  name: nu_nl_algemeen
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
  ```
