### ISSUE TITLE
Feed sensor return empty state for valid rss

### ISSUE THREAD

**Issue by juliomatcom** [custom-components/feedparser#112]
Hi all,  I'm using the next configuration but no entries are retrieved

```yml
sensor:
  - platform: feedparser
    name: elcomercio
    feed_url: 'https://www.elcomercio.es/rss/2.0/?section=gijon'
    show_topn: 20
    scan_interval:
      hours: 1
```

![screenshot-hass lan-2023 12 10-11_59_29](https://github.com/custom-components/feedparser/assets/8549955/2841e825-d399-4fa6-8804-c84975e1188f)

It does work with the example provided so I guess it should be related to the `xml` format or the response somehow.
