### ISSUE TITLE
UnknownTimezoneWarning Error

### ISSUE THREAD

**Issue by vanislman** [custom-components/feedparser#132]
My CBC newsfeeds stopped working a few weeks ago, and looking at the log file I see following error message:

```
Logger: py.warnings
Source: custom_components/feedparser/sensor.py:122
integration: feedparser ([documentation](https://github.com/custom-components/feedparser/blob/master/README.md))
First occurred: 17:46:32 (1 occurrences)
Last logged: 17:46:32
/usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood. Pass `tzinfos` argument in order to correctly return a timezone-aware datetime. In a future version, this will raise an exception. warnings.warn("tzname {tzname} identified but not understood. "
```

My configuration for this newsfeed is:
```yaml
  - platform: feedparser
    name: CBC Business
    feed_url: 'https://www.cbc.ca/cmlink/rss-business'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 2
```
