### ISSUE TITLE
Unsure if installing correctly

### ISSUE THREAD

**Issue by MattDemers** [custom-components/feedparser#142]
I've installed `feedparser` as a custom component through HACS (using Docker HomeAssistant, everything's latest). I can confirm through FTP that `feedparser` is in my `custom_compontents` directory.

This is my `configuration.yaml`. I'm using the example that you posted in the README.md.

Unfortunately, after restarting HomeAssistant after install (and after restarts due to tweaking the YAML) I don't see a new sensor inside the Developer > States menu. Unfortunately the only thing involving Feedparser there seems to be the HACS sensor for notifying for updates.

```
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'   
  - platform: feedparser
    name: Engineering Feed
    feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language
```

**Comment by rjmccallumbigl** [comment]
I wondered the same but I needed an extra restart to get mine working. 
1. I installed through HACS as well
2. Restarted Hassio
3. Added this to my configuration.yaml:
```yaml
sensor:
  - platform: feedparser
    name: TIL
    feed_url: 'https://www.reddit.com/r/todayilearned.rss'                
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3                                           
```
4. And restarted again, now I can see the entity:

![Image](https://github.com/user-attachments/assets/ebebd539-75c1-49b1-8f6a-1cc87d0d06c0)

![Image](https://github.com/user-attachments/assets/b661e063-a640-4d5a-8ae8-186a81e613e9)
