### ISSUE TITLE
Can not get <description> with https://vnexpress.net/rss/tin-moi-nhat.rss

### ISSUE THREAD

**Issue by khaisilk1910** [custom-components/feedparser#144]
![Image](https://github.com/user-attachments/assets/3aad303e-1173-4aa7-8439-073bb98a7b58)
I want get <description> but can not get that content.
Other content can get good.
How to can i get description

`sensor:
  platform: feedparser
  name: Engineering Feed
  feed_url: 'https://[vnexpress.net/rss/tin-moi-nhat.rss](https://vnexpress.net/rss/tin-moi-nhat.rss'
  date_format: '%a, %d %b %Y %H:%M:%S %Z'
  scan_interval:
    hours: 3
  inclusions:
    - title
    - link
    - description
    - image
    - pubDate`

Thanks

**Comment by Dynamix72** [comment]
Use - summary instead of description

```
  - platform: feedparser 
    name: Engineering 
    feed_url: 'https://vnexpress.net/rss/tin-moi-nhat.rss' 
    scan_interval: 
      hours: 3 
    show_topn: 10
    inclusions:
      - title
      - summary
      - link
      - image 
      - pubDate
```

**Comment by Dynamix72** [comment]
With Flex-table-card you can have all the items you want.

![Image](https://github.com/user-attachments/assets/f6f10d89-11eb-4ece-ae7d-f02162590c98)

```
type: custom:flex-table-card
title: News
entities:
  include:
    - sensor.engineering
max_rows: 5
columns:
  - name: ""
    data: entries
    modify: "'<img src=\"' + x.image + '\"height=100>'"
  - name: ""
    data: entries
    modify: >-
      var value1=String(x.summary.split('</a>')[0]); var
      value2=String(x.summary.split('</a>')[1]);  '<b><u>' + x.title +
      '</b></u><br>' + value2 
css:
  tbody tr td:first-child+: "padding-left: 0px"
  tbody tr td+: "a { color: inherit; text-decoration: none;"
  thead th: "display: none;"
  table: "padding: 0px 16px 16px"
  tbody tr:nth-child(odd)+: "background-color: inherit"
```
