### ISSUE TITLE
showrss compatibility?

### ISSUE THREAD

**Issue by gurkburk76** [custom-components/feedparser#24]
Not sure if it's showrss fault or this plugin, but when i use it to get stuff from there it won't show in home assistant.
Any way to get around this or make it compatible ?
showrss.info

**Comment by ogajduse** [comment]
Works for me.

Using the following config
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://showrss.info/show/1103.rss
  inclusions:
  - image
  - title
  - link
  - published
  local_time: false
  name: showrss_sex_education
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
  ```
![image](https://github.com/custom-components/feedparser/assets/20440883/140ac740-8604-4426-b7d7-5d21e0ddd3e0)

**Comment by ogajduse** [comment]
@gurkburk76 Do you still face the issue?

**Comment by hjallex** [comment]
Hi,

I think I have the same problem.
I have tryed your exampel @ogajduse but it will give me the same result as my own code.
The /config/configuration.yaml code is green and a restart of homeassistant is possible.
I have also tested to switch browsers, units and apps.

My code is:
```
sensor:
  - platform: feedparser
    name: RSS_DN
    feed_url: 'http://www.dn.se/nyheter/m/rss/'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language

```
When I go to Deweloptools and search for entity: rss_dn nothing will come up...

Please give me some help.
Thank you!

**Comment by ogajduse** [comment]
@hjallex I forgot to mention that I tested it with the `0.2.0b2` pre-release. I plan to release 0.2.0 and there are some beta releases available. I would be more than grateful if the community would try the beta releases before I release it.

Could you please try installing the `0.2.0b2` release [through HACS](https://hacs.xyz/docs/faq/beta/) and let me know if it works for you?

**Comment by hjallex** [comment]
I have updated to your 0.2.0b2 beta version with hacks.
Restarted HA.
Tryed to find "RSS_DN" or "showrss" but nothing. 
So I was making some adjustment in the yalm.
But it did't work.

My yalm file is green and when I go to next site for "check configuration and restart button" I got an error.
I have tryed with "sensor" and without sensor.
I'm send you some copy from my yalm and restart site. This is my latest test. 


My yalm code:


```
#sensor:
  - platform: feedparser
    name: RSS_DN
    feed_url: 'http://www.dn.se/nyheter/m/rss/'
#    feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language
    
sensor:
  - platform: feedparser
    name: Engineering Feed
    feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language
```
    
    
My error:
Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 57).
Invalid config for [sensor.integration]: [unit_of_measurement] is an invalid option for [sensor.integration]. Check: sensor.integration->unit_of_measurement. (See ?, line ?).
Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 57).
![Skärmbild 2023-08-12 132819](https://github.com/custom-components/feedparser/assets/74986552/76b6db67-9207-4f68-9b32-62d4c1fa7a31)
![Skärmbild 2023-08-12 132710](https://github.com/custom-components/feedparser/assets/74986552/55c3741c-4602-49d7-a080-11f801eef384)


With your exampel from above:
    
    
```
#sensor:    
  - feedparser:
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
#    exclusions: []
    feed_url: 'https://showrss.info/show/1103.rss'
    inclusions:
     - image
     - title
     - link
     - published
    local_time: false
    name: showrss_sex_education
#   platform: feedparser
    scan_interval:
        seconds: 3600
    show_topn: 9999
  - date_format: '%a, %d %b %Y %H:%M:%S %z'
#  exclusions: []
    feed_url: https://showrss.info/show/1103.rss
    inclusions:
    - image
    - title
    - link
    - published
    local_time: false
    name: showrss_sex_education
    platform: feedparser
    scan_interval:
      seconds: 3600
    show_topn: 9999
```
    
I can make a correct restart but I cant find the "name: showrss_sex_education" in the list.
My conclusion is: the beta version is not working ether.

Thank you!

**Comment by ogajduse** [comment]
I have successfully used the config that you posted and feedparser 0.2.0b2  correctly populates the data to the sensor.

```yaml
sensor:
  - platform: feedparser
    name: RSS_DN
    feed_url: 'http://www.dn.se/nyheter/m/rss/'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language    

  - platform: feedparser
    name: Engineering Feed
    feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      hours: 3
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language
```

![image](https://github.com/custom-components/feedparser/assets/20440883/c9578dc9-234d-4a20-b729-4266dcb9dc27)
![image](https://github.com/custom-components/feedparser/assets/20440883/c1667b42-d497-4a3b-b015-e7be239ad45a)


I am looking at the screenshot of `configuration.yaml` that you included.
Beware that the `sensor` section has to be defined only once. Also for every sensor entry in the configuration, you have to specify `platform` - in our case, it is `feedparser` Lines 45-59 should be placed under line 79 as all sensors need to be nested under the `sensor` section.

If you have troubles with configuration

Note: I would recommend you use `published` instead of `pubDate`. That adds the date to the feed entry in the sensor. I see that it is not well documented in the README, so I have created #90 to address it.
