### ISSUE TITLE
Platform error sensor.feedparser

### ISSUE THREAD

**Issue by HeedfulCrayon** [custom-components/feedparser#36]
Just discovered this component today and wanted to use it to track unifi firmware releases for my UDM.  Running home assistant on Proxmox using the whiskerz script.

Config Entry:
```
sensor:
  platform: feedparser
  name: UDM Firmware
  feed_url: "https://community.ui.com/rss/releases/UniFi-Dream-Machine-Firmware/b0f0a740-021e-4027-a778-ceba983be74b"
```

Config Error:
```
Platform error sensor.feedparser - cannot import name 'SensorEntity' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```
