### ISSUE TITLE
Cant read description with ![CDATA]

### ISSUE THREAD

**Issue by sljdhl** [custom-components/feedparser#42]
Hello. Im trying to read out the school meal from this https://skolmaten.se/ede-skola/rss/weeks/?limit=2,

However the description is not read, possibly due to ![CDATA]? It appears to be valid in XML. Any ideas?

**Comment by dvesters** [comment]
I have the same problem with [https://data.buienradar.nl/1.0/feed/xml/rssbuienradar](url)

`<description>`
      `<![CDATA[ ` message.here  `]]>`
`</description>`

**Comment by jgallis** [comment]
I have the same problem with https://api.met.no/weatherapi/metalerts/1.1/

**Comment by IanLJohnson** [comment]
Apologies for joining the party so late.
According to the documentation of [feedparser](https://pythonhosted.org/feedparser/) some fields seem to be renamed, e.g. description => summary and pubDate => published. It took me quite a while to realize this as I too thought it was some kind of parsing bug.

**Comment by ExMacro** [comment]
> According to the documentation of [feedparser](https://pythonhosted.org/feedparser/) some fields seem to be renamed, e.g. description => summary and pubDate => published. It took me quite a while to realize this as I too thought it was some kind of parsing bug.
Thanks! I had a similar parsing issue but got it working with the summary tag. Description is all over the documentation but it doesn't seem to work anymore.

**Comment by qJake** [comment]
I have the same issue with this feed:

https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml

Any way we can help get this fixed?

**Comment by ogajduse** [comment]
@qJake Could you share your YAML config for the stream you shared?

**Comment by ogajduse** [comment]
> > According to the documentation of [feedparser](https://pythonhosted.org/feedparser/) some fields seem to be renamed, e.g. description => summary and pubDate => published. It took me quite a while to realize this as I too thought it was some kind of parsing bug.
> 
> Thanks! I had a similar parsing issue but got it working with the summary tag. Description is all over the documentation but it doesn't seem to work anymore.

Using https://data.buienradar.nl/1.0/feed/xml/rssbuienradar

```yaml
- exclusions: []
  feed_url: https://data.buienradar.nl/1.0/feed/xml/rssbuienradar
  inclusions:
  - image
  - title
  - link
  - published
  local_time: false
  name: 'buienradar_nl '
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
  ```
For each entry in the parsed feed `entry.summary == entry.description`.

Could someone confirm that this issue still persists?

**Comment by ogajduse** [comment]
@sljdhl Using the latest beta version, feedparser correctly reads the data correctly. 

My sensor config:
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://skolmaten.se/ede-skola/rss/weeks/?limit=2
  inclusions:
  - title
  - link
  - published
  - summary
  local_time: false
  name: skolmaten_se_ede_skola
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
  ```
  
How it shows in developer tools
![image](https://github.com/custom-components/feedparser/assets/20440883/00de013a-d4d0-499a-9a31-6e9dce6af667)

How it renders in Lovelace using [list-card](https://github.com/iantrich/list-card):
![image](https://github.com/custom-components/feedparser/assets/20440883/2d714aa7-9cf6-4ed8-97ba-546fbf031e49)

**Comment by ogajduse** [comment]
@dvesters Same here, using the latest beta version, I got the following results:

In Lovelace:
![image](https://github.com/custom-components/feedparser/assets/20440883/6a1821e6-b870-4ef4-9ecd-3df040778ef2)

In developer tools:
![image](https://github.com/custom-components/feedparser/assets/20440883/b41cd925-5e0d-4b8f-a50f-ae0bfc62ab8e)


Sensor config:
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://data.buienradar.nl/1.0/feed/xml/rssbuienradar
  inclusions:
  - image
  - title
  - link
  - published
  local_time: false
  name: buienradar_nl
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
```

Lovelace config:
```yaml
type: custom:list-card
entity: sensor.buienradar_nl
title: Test feed
feed_attribute: entries
columns:
  - title: ''
    type: image
    add_link: link
    field: image
  - title: Title
    field: title
    style:
      - white-space: wrap
    add_link: link
  - title: Published
    field: published
```

**Comment by ogajduse** [comment]
> Apologies for joining the party so late. According to the documentation of [feedparser](https://pythonhosted.org/feedparser/) some fields seem to be renamed, e.g. description => summary and pubDate => published. It took me quite a while to realize this as I too thought it was some kind of parsing bug.

README.md will be fixed as a part of #90.

**Comment by ogajduse** [comment]
> I have the same problem with [api.met.no/weatherapi/metalerts/1.1](https://api.met.no/weatherapi/metalerts/1.1/)

@jgallis 
Works for me using the latest beta version.

config:
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://api.met.no/weatherapi/metalerts/1.1/
  inclusions:
  - title
  - link
  - published
  - summary
  local_time: false
  name: api_met_no_metalerts
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
```

lovelace config:
```yaml
type: custom:list-card
entity: sensor.api_met_no_metalerts
title: Test feed
feed_attribute: entries
columns:
  - title: Title
    field: title
    style:
      - white-space: wrap
    add_link: link
  - title: Published
    field: published
```

sensor with its attributes in UI:
![image](https://github.com/custom-components/feedparser/assets/20440883/4a1335c1-1d10-4c20-a33a-5e4e67b8d892)

How it shows in Lovelace using [list-card](https://github.com/iantrich/list-card):
![image](https://github.com/custom-components/feedparser/assets/20440883/b3b49b5e-8efe-44c1-87b8-20576c3a3e6e)
