### ISSUE TITLE
Feedparser sensor reporting "unknown" state after update to v0.1.7

### ISSUE THREAD

**Issue by jazzyisj** [custom-components/feedparser#51]
After update to v0.1.7 the state is reporting unknown.  State attributes (feed items) are working correctly.

![image](https://user-images.githubusercontent.com/44064559/132727054-2cfa07cb-42bf-4cf9-a3be-5fce36604477.png)

If I roll back to v0.1.6 it reports the number of feed entries again.

![image](https://user-images.githubusercontent.com/44064559/132728223-8df8c61b-0709-4f60-9295-d93ce90705ea.png)

My feed parser config.

```
  - platform: feedparser
    name: Home Assistant Alerts
    feed_url: https://alerts.home-assistant.io/feed.xml
    date_format: '%Y-%m-%d'
    inclusions:
      - title
      - updated
      - content
      - link
    exclusions:
      - language
```
