### ISSUE TITLE
Cant pars rss feed

### ISSUE THREAD

**Issue by Bram-diederik** [custom-components/feedparser#65]
I want the news podcast over my speakers but i cant parse the rss feed. Gives a empty result.

``` - platform: feedparser
    name: anp nieuws
    feed_url: https://www.omnycontent.com/d/playlist/56ccbbb7-0ff7-4482-9d99-a88800f49f6c/a49c87f6-d567-4189-8692-a8e2009eaf86/9fea2041-fccd-4fcf-8cec-a8e2009eeca2/podcast.rss
    scan_interval:
      hours: 0.5
    show_topn: 1
    inclusions:
    - media
    - title```

**Comment by Aasikki** [comment]
Same, issue with this rss feed:
https://kimmo.suominen.com/stuff/fingerpori.xml

![image](https://user-images.githubusercontent.com/58399890/224394050-7fff6421-bfe7-4b2c-af5d-7347eabcc855.png)

Tried with and without filters, nothing.

**Comment by ogajduse** [comment]
@Bram-diederik 
I have slightly modified your config and I was able to parse the feed using the latest beta release of the feedparser component.

my config:
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://www.omnycontent.com/d/playlist/56ccbbb7-0ff7-4482-9d99-a88800f49f6c/a49c87f6-d567-4189-8692-a8e2009eaf86/9fea2041-fccd-4fcf-8cec-a8e2009eeca2/podcast.rss
  inclusions:
  - title
  - link
  - published
  - summary
  local_time: false
  name: anp_nieuws
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
```

Lovelace config:
```yaml
type: custom:list-card
entity: sensor.anp_nieuws
title: Test feed
feed_attribute: entries
columns:
  - title: Title
    field: title
    style:
      - white-space: wrap
    add_link: link
  - title: Summary
    field: summary
  - title: Published
    field: published
```

The sensor in UI:
![image](https://github.com/custom-components/feedparser/assets/20440883/b42085db-d59f-4bf9-bfae-7006dad81834)

How it appears in Lovelace using [list-card](https://github.com/iantrich/list-card):
![image](https://github.com/custom-components/feedparser/assets/20440883/c58a280f-fcda-4e01-be1a-77ed17f4fb80)

If you click on the title, the browser starts downloading the podcast.

I would be grateful if the community tried the beta releases before I release it.
Could you please try installing the `0.2.0b4` release [through HACS](https://hacs.xyz/docs/faq/beta/) and let me know if it works for you?

**Comment by Bram-diederik** [comment]
I have made a php script that direcly gets the latest news. I use that for
my automation.

Op vr 18 aug. 2023 11:56 schreef Ondřej Gajdušek ***@***.***>:

**Comment by ogajduse** [comment]
> Same, issue with this rss feed: [kimmo.suominen.com/stuff/fingerpori.xml](https://kimmo.suominen.com/stuff/fingerpori.xml)
> 
> ![image](https://user-images.githubusercontent.com/58399890/224394050-7fff6421-bfe7-4b2c-af5d-7347eabcc855.png)
> 
> Tried with and without filters, nothing.

@Aasikki
I have tested the feed that you provided and it works for me. Here are my configs and screenshots.

configuration.yaml
```yaml
- date_format: '%a, %d %b %Y %H:%M:%S UTC%z'
  exclusions: []
  feed_url: https://kimmo.suominen.com/stuff/fingerpori.xml
  inclusions:
  - title
  - link
  - published
  - summary
  - image
  local_time: false
  name: kimmo_suominen_fingerpori
  platform: feedparser
  scan_interval:
    seconds: 3600
  show_topn: 9999
```

lovelace config:
```yaml
type: custom:list-card
entity: sensor.kimmo_suominen_fingerpori
title: Test feed
feed_attribute: entries
columns:
  - title: Title
    field: title
    style:
      - white-space: wrap
    add_link: link
  - title: ''
    type: image
    add_link: link
    width: 500
    height: null
    field: image
  - title: Published
    field: published
```


Screen shot from developer tools:
![image](https://github.com/custom-components/feedparser/assets/20440883/425543fb-d59e-40a2-9e45-9ac5f26cd2dd)

Screen shot from Lovelace:

![image](https://github.com/custom-components/feedparser/assets/20440883/509f211c-6ff7-4f71-bbcc-70a6a7588a17)
