### ISSUE TITLE
No more images after update 0.1.8 -> 0.1.11

### ISSUE THREAD

**Issue by BebeMischa** [custom-components/feedparser#78]
Hello guys and girls,

I've just updated and now I have no more images in my feed. Something I need to change or is it a bug?

My feed sensor:

```
  - platform: feedparser
    name: Het nieuws
    feed_url: 'https://www.nu.nl/rss'
    date_format: '%a, %d %b %Y %H:%M:%S %Z'
    scan_interval:
      minutes: 1
    inclusions:
      - title
      - link
      - description
      - image
      - pubDate
    exclusions:
      - language

```

result: 

![afbeelding](https://github.com/custom-components/feedparser/assets/73079275/f066c407-7dab-4420-9b05-23a9e9091070)

Before this update it worked fine...
